name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install llvm 16
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16 && rm llvm.sh
    - name: Install riscv64 target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build
      run: cargo build --verbose --release --target=riscv64imac-unknown-none-elf
    - name: Install debugger
      run: curl -LO https://github.com/nervosnetwork/ckb-standalone-debugger/releases/download/v0.112.1/ckb-debugger-linux-x64.tar.gz && tar xzf ckb-debugger-linux-x64.tar.gz && rm ckb-debugger-linux-x64.tar.gz
    - name: Run the contract with debugger
      run: ./ckb-debugger --bin target/riscv64imac-unknown-none-elf/release/ckb-contract-bytes-without-a --script-version=1
